#!/bin/bash
# 🍯 HONEY PROJECT - DEPLOYMENT CHECKLIST
# Quick reference for Docker & Kubernetes setup

set -e

echo "=========================================="
echo "🍯 HONEY PROJECT DEPLOYMENT CHECKLIST"
echo "=========================================="
echo ""

# PHASE 1: Docker Build
echo "📦 PHASE 1: DOCKER IMAGE BUILD"
echo "-------------------------------------------"
echo "Status: Required before Kubernetes deployment"
echo ""
echo "Run these commands:"
echo ""
echo "  1. Build Frontend:"
echo "     docker build -t beeyield-frontend:latest ."
echo ""
echo "  2. Build Backend:"
echo "     docker build -t beeyield-backend:latest ./backend"
echo ""
echo "  3. Verify images:"
echo "     docker images | grep beeyield"
echo ""
echo "-------------------------------------------"
echo ""

# PHASE 2: Kubernetes Secrets
echo "🔐 PHASE 2: UPDATE KUBERNETES SECRETS"
echo "-------------------------------------------"
echo "Status: Configured but needs your values"
echo ""
echo "Edit file: k8s/secrets.yaml"
echo "Update values:"
echo "  - DATABASE_URL"
echo "  - SUPABASE_URL"
echo "  - SUPABASE_KEY"
echo ""
echo "Command:"
echo "  kubectl apply -f k8s/secrets.yaml"
echo ""
echo "-------------------------------------------"
echo ""

# PHASE 3: Deploy to Kubernetes
echo "☸️  PHASE 3: DEPLOY TO KUBERNETES"
echo "-------------------------------------------"
echo "Status: All manifests ready"
echo ""
echo "Option A - Deploy everything at once:"
echo "  kubectl apply -k k8s/"
echo ""
echo "Option B - Deploy step by step:"
echo "  kubectl apply -f k8s/namespace.yaml"
echo "  kubectl apply -f k8s/configmap.yaml"
echo "  kubectl apply -f k8s/secrets.yaml"
echo "  kubectl apply -f k8s/postgres-pvc.yaml"
echo "  kubectl apply -f k8s/redis-pvc.yaml"
echo "  kubectl apply -f k8s/postgres-deployment.yaml"
echo "  kubectl apply -f k8s/redis-deployment.yaml"
echo "  kubectl apply -f k8s/frontend-deployment.yaml"
echo "  kubectl apply -f k8s/backend-deployment.yaml"
echo "  kubectl apply -f k8s/services.yaml"
echo "  kubectl apply -f k8s/ingress.yaml"
echo "  kubectl apply -f k8s/hpa.yaml"
echo ""
echo "-------------------------------------------"
echo ""

# PHASE 4: Verify Deployment
echo "✅ PHASE 4: VERIFY DEPLOYMENT"
echo "-------------------------------------------"
echo "Status: Verification commands"
echo ""
echo "Monitor deployment progress:"
echo "  kubectl rollout status deployment/beeyield-frontend -n beeyield"
echo "  kubectl rollout status deployment/beeyield-backend -n beeyield"
echo "  kubectl rollout status deployment/beeyield-postgres -n beeyield"
echo "  kubectl rollout status deployment/beeyield-redis -n beeyield"
echo ""
echo "View all resources:"
echo "  kubectl get all -n beeyield"
echo ""
echo "Check pod status:"
echo "  kubectl get pods -n beeyield -o wide"
echo ""
echo "View logs:"
echo "  kubectl logs -f deployment/beeyield-frontend -n beeyield"
echo "  kubectl logs -f deployment/beeyield-backend -n beeyield"
echo ""
echo "-------------------------------------------"
echo ""

# PHASE 5: Configure Ingress
echo "🌐 PHASE 5: CONFIGURE INGRESS"
echo "-------------------------------------------"
echo "Status: Requires domain names"
echo ""
echo "Edit file: k8s/ingress.yaml"
echo "Update:"
echo "  - beeyield.example.com → your-frontend-domain"
echo "  - api.beeyield.example.com → your-api-domain"
echo ""
echo "Enable TLS (optional):"
echo "  1. Uncomment tls section in ingress"
echo "  2. Install cert-manager: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.yaml"
echo "  3. Create ClusterIssuer for Let's Encrypt"
echo ""
echo "Apply ingress:"
echo "  kubectl apply -f k8s/ingress.yaml"
echo ""
echo "-------------------------------------------"
echo ""

# PHASE 6: Docker Compose (Alternative)
echo "🐳 PHASE 6: DOCKER COMPOSE (ALTERNATIVE TO K8S)"
echo "-------------------------------------------"
echo "Status: Simpler, single-host deployment"
echo ""
echo "For development:"
echo "  docker compose -f docker-compose.dev.yml up -d"
echo ""
echo "For production:"
echo "  docker compose -f docker-compose.yml up -d"
echo ""
echo "Stop services:"
echo "  docker compose down"
echo ""
echo "View logs:"
echo "  docker compose logs -f"
echo ""
echo "-------------------------------------------"
echo ""

# Summary
echo "=========================================="
echo "📋 QUICK SUMMARY"
echo "=========================================="
echo ""
echo "✅ Docker Status:"
echo "   Version: $(docker --version)"
echo "   Containers: $(docker ps -q | wc -l) running"
echo "   Images: $(docker images | tail -n +2 | wc -l) total"
echo ""
echo "✅ Kubernetes Status:"
echo "   Version: $(kubectl version --short 2>/dev/null | grep Server || echo 'Not installed')"
echo "   Nodes: $(kubectl get nodes --no-headers 2>/dev/null | wc -l) ready"
echo "   Namespaces: beeyield, beeyield-prod (created)"
echo ""
echo "📊 BeeYield Namespace Status:"
kubectl get all -n beeyield 2>/dev/null | tail -n +2 || echo "   (Deployments pending image builds)"
echo ""
echo "=========================================="
echo "🚀 NEXT STEPS:"
echo "=========================================="
echo ""
echo "1️⃣  Build Docker images:"
echo "   docker build -t beeyield-frontend:latest ."
echo "   docker build -t beeyield-backend:latest ./backend"
echo ""
echo "2️⃣  Deploy to Kubernetes:"
echo "   kubectl apply -k k8s/"
echo ""
echo "3️⃣  Verify deployment:"
echo "   kubectl get pods -n beeyield -w"
echo ""
echo "=========================================="
echo ""
