apiVersion: v1
kind: ConfigMap
metadata:
  name: beeyield-config
  namespace: beeyield
data:
  PYTHONUNBUFFERED: "1"
  NODE_ENV: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beeyield-config
  namespace: beeyield-prod
data:
  PYTHONUNBUFFERED: "1"
  NODE_ENV: "production"
