apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: beeyield

commonLabels:
  app.kubernetes.io/name: beeyield
  app.kubernetes.io/instance: production

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- postgres-pvc.yaml
- postgres-deployment.yaml
- redis-pvc.yaml
- redis-deployment.yaml
- frontend-deployment.yaml
- backend-deployment.yaml
- services.yaml
- ingress.yaml
- hpa.yaml
