-- ============================================
-- BeeYield COMPLETE Database Schema for Supabase
-- All tables for all pages, synchronized with backend schemas
-- ============================================

-- ============================================
-- 1. E-COMMERCE TABLES (Shop, Checkout)
-- ============================================

-- Products Table
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL, -- 'honey', 'merch', 'education'
    badge TEXT, -- 'Bestseller', 'New', 'Premium'
    images TEXT[] DEFAULT '{}',
    rating FLOAT DEFAULT 5.0,
    review_count INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Product Variants (Sizes/Types)
CREATE TABLE IF NOT EXISTS product_variants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID REFERENCES products(id) ON DELETE CASCADE,
    size TEXT NOT NULL, -- '500g', '1kg', 'L', 'XL', 'PDF'
    price_kes DECIMAL(10, 2) NOT NULL,
    stock_quantity INTEGER DEFAULT 100,
    is_available BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number TEXT NOT NULL UNIQUE,
    user_id UUID, -- Optional, for logged in users
    status TEXT DEFAULT 'pending', -- 'pending', 'paid', 'shipped', 'completed', 'cancelled'
    payment_method TEXT, -- 'mpesa', 'card'
    payment_status TEXT DEFAULT 'pending',
    total_kes DECIMAL(10, 2) NOT NULL,
    shipping_address JSONB,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
    product_id UUID REFERENCES products(id),
    variant_id UUID REFERENCES product_variants(id),
    product_name TEXT,
    variant_size TEXT,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ============================================
-- 2. TRACEABILITY TABLES (Blockchain Powered)
-- ============================================

-- Farmers / Beekeepers
CREATE TABLE IF NOT EXISTS farmers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    farmer_id TEXT UNIQUE, -- UUID generated by service
    name TEXT NOT NULL,
    phone TEXT,
    id_number TEXT,
    experience_years INTEGER DEFAULT 0,
    story TEXT,
    latitude FLOAT,
    longitude FLOAT,
    location_name TEXT,
    region TEXT,
    county TEXT,
    ward TEXT,
    registration_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    certification_status TEXT DEFAULT 'PENDING', -- PENDING, CERTIFIED, REJECTED
    total_hives INTEGER DEFAULT 0,
    blockchain_hash TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Apiaries (Bee Yards)
CREATE TABLE IF NOT EXISTS apiaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    apiary_id TEXT UNIQUE, -- UUID generated by service
    apiary_code TEXT NOT NULL UNIQUE, -- e.g. NYR-001
    name TEXT NOT NULL,
    farmer_id UUID REFERENCES farmers(id),
    environment_type TEXT, -- 'Forest', 'Savannah', 'Coastal', 'Mountain'
    flora_types TEXT[] DEFAULT '{}',
    water_source TEXT,
    sun_exposure TEXT DEFAULT 'Full Sun',
    latitude FLOAT,
    longitude FLOAT,
    location_name TEXT,
    region TEXT,
    county TEXT,
    ward TEXT,
    hive_count INTEGER DEFAULT 0,
    established_date DATE,
    image_url TEXT,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    blockchain_hash TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Hives Table
CREATE TABLE IF NOT EXISTS hives (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hive_id TEXT UNIQUE, -- UUID generated by service
    hive_code TEXT NOT NULL UNIQUE,
    apiary_id UUID REFERENCES apiaries(id),
    farmer_id UUID REFERENCES farmers(id),
    hive_type TEXT, -- 'Langstroth', 'KTBH', 'Traditional'
    bee_type TEXT DEFAULT 'African Honey Bee',
    queen_type TEXT,
    frame_count INTEGER DEFAULT 0,
    material TEXT DEFAULT 'Wood',
    installation_date DATE,
    has_sensors BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE, DAMAGED
    last_inspection DATE,
    blockchain_hash TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Harvests Table
CREATE TABLE IF NOT EXISTS harvests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    harvest_id TEXT UNIQUE, -- UUID generated by service
    harvest_code TEXT UNIQUE,
    hive_id UUID REFERENCES hives(id),
    farmer_id UUID REFERENCES farmers(id),
    harvest_date DATE NOT NULL,
    quantity_kg DECIMAL(10, 2),
    quantity_left_for_bees_kg DECIMAL(10, 2),
    extraction_method TEXT,
    nectar_source TEXT,
    weather_conditions TEXT,
    moisture_content_percent FLOAT,
    quality_score INTEGER,
    blockchain_hash TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Processing Records Table
CREATE TABLE IF NOT EXISTS processing_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    harvest_id UUID REFERENCES harvests(id),
    processing_date DATE NOT NULL,
    processor_name TEXT,
    facility_location TEXT,
    filtering_method TEXT,
    moisture_content_percent FLOAT,
    temperature_celsius FLOAT,
    is_raw BOOLEAN DEFAULT true,
    blockchain_hash TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Batches Table (Final packaged product)
CREATE TABLE IF NOT EXISTS batches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    batch_code TEXT NOT NULL UNIQUE, -- This is what customers scan
    processing_id UUID REFERENCES processing_records(id),
    product_id UUID REFERENCES products(id),
    packaging_date DATE,
    expiry_date DATE,
    quantity_jars INTEGER,
    jar_size_grams INTEGER,
    blockchain_hash TEXT,
    qr_code_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ============================================
-- 3. CONTACT & FORMS TABLES
-- ============================================

-- Contact Submissions
CREATE TABLE IF NOT EXISTS contact_submissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    inquiry_type TEXT NOT NULL, -- 'grower', 'beekeeper', 'general'
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    company TEXT,
    topic TEXT,
    message TEXT,
    form_specific_data JSONB,
    status TEXT DEFAULT 'new', -- 'new', 'in_progress', 'resolved'
    replied_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Pollination Requests
CREATE TABLE IF NOT EXISTS pollination_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    farm_name TEXT NOT NULL,
    farm_location TEXT,
    crop_type TEXT NOT NULL,
    acres INTEGER,
    preferred_start_date DATE,
    additional_info TEXT,
    status TEXT DEFAULT 'pending', -- 'pending', 'contacted', 'scheduled', 'completed'
    assigned_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Newsletter Subscriptions
CREATE TABLE IF NOT EXISTS newsletter_subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL UNIQUE,
    first_name TEXT,
    source TEXT, -- 'footer', 'popup', 'shop', 'blog'
    is_active BOOLEAN DEFAULT true,
    subscribed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    unsubscribed_at TIMESTAMP WITH TIME ZONE
);

-- ============================================
-- 4. CAREERS / JOBS TABLES
-- ============================================

-- Job Listings
CREATE TABLE IF NOT EXISTS job_listings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    department TEXT,
    location TEXT NOT NULL,
    job_type TEXT NOT NULL, -- 'Full-time', 'Part-time', 'Contract', 'Internship'
    description TEXT,
    requirements TEXT[],
    benefits TEXT[],
    salary_range TEXT,
    is_active BOOLEAN DEFAULT true,
    posted_date DATE DEFAULT CURRENT_DATE,
    closing_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Job Applications
CREATE TABLE IF NOT EXISTS job_applications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id UUID REFERENCES job_listings(id),
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    resume_url TEXT, -- Stored in Supabase Storage
    cover_letter TEXT,
    linkedin_url TEXT,
    portfolio_url TEXT,
    experience_years INTEGER,
    status TEXT DEFAULT 'new', -- 'new', 'screening', 'interview', 'rejected', 'hired'
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ============================================
-- 5. BLOG / CMS TABLES
-- ============================================

-- Blog Posts
CREATE TABLE IF NOT EXISTS blog_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    excerpt TEXT,
    content TEXT,
    featured_image TEXT,
    category TEXT,
    tags TEXT[],
    author_name TEXT,
    author_image TEXT,
    read_time_minutes INTEGER DEFAULT 5,
    status TEXT DEFAULT 'draft', -- 'draft', 'published', 'archived'
    views_count INTEGER DEFAULT 0,
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Media/Press Releases
CREATE TABLE IF NOT EXISTS media_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    slug TEXT UNIQUE,
    type TEXT NOT NULL, -- 'press_release', 'news', 'award', 'video'
    summary TEXT,
    content TEXT,
    image_url TEXT,
    external_url TEXT,
    source TEXT, -- 'Nation', 'Business Daily', etc.
    published_date DATE,
    is_featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ============================================
-- 6. COMPANY / TEAM TABLES
-- ============================================

-- Team Members
CREATE TABLE IF NOT EXISTS team_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    department TEXT,
    bio TEXT,
    image_url TEXT,
    email TEXT,
    linkedin_url TEXT,
    twitter_url TEXT,
    is_leadership BOOLEAN DEFAULT false,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Company Stats/Metrics
CREATE TABLE IF NOT EXISTS company_stats (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    stat_key TEXT NOT NULL UNIQUE,
    stat_value TEXT NOT NULL,
    stat_label TEXT NOT NULL,
    stat_description TEXT,
    icon TEXT,
    category TEXT DEFAULT 'impact',
    display_order INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Company Milestones (Our Story)
CREATE TABLE IF NOT EXISTS company_milestones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    year INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    milestone_type TEXT DEFAULT 'general', -- 'founding', 'growth', 'technology', 'expansion', 'milestone'
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Partners/Certifications
CREATE TABLE IF NOT EXISTS partners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    type TEXT, -- 'partner', 'certification', 'investor'
    logo_url TEXT,
    website_url TEXT,
    description TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- FAQs
CREATE TABLE IF NOT EXISTS faqs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    category TEXT, -- 'Orders', 'Products', 'Shipping', 'Services'
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ============================================
-- 7. POLLINATION & SERVICES TABLES
-- ============================================

-- Pollination Services (Description of offerings)
CREATE TABLE IF NOT EXISTS pollination_services (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    short_description TEXT,
    image_url TEXT,
    icon TEXT,
    features TEXT[] DEFAULT '{}',
    benefits TEXT[] DEFAULT '{}',
    pricing_info TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Pollination Packages (Actual items for sale/request)
CREATE TABLE IF NOT EXISTS pollination_packages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE,
    description TEXT,
    price_per_acre DECIMAL(10, 2),
    min_acres INTEGER DEFAULT 10,
    hives_per_acre FLOAT DEFAULT 2.0,
    features TEXT[],
    is_featured BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Crops Pollinated
CREATE TABLE IF NOT EXISTS crops_pollinated (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    image_url TEXT,
    icon TEXT,
    pollination_info TEXT,
    season TEXT,
    region TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ESG Metrics
CREATE TABLE IF NOT EXISTS esg_metrics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    metric_key TEXT NOT NULL,
    metric_name TEXT NOT NULL,
    metric_value FLOAT NOT NULL,
    metric_unit TEXT,
    category TEXT NOT NULL, -- 'environmental', 'social', 'governance'
    description TEXT,
    reporting_period TEXT,
    year INTEGER NOT NULL,
    is_verified BOOLEAN DEFAULT false,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Impact Stories
CREATE TABLE IF NOT EXISTS impact_stories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    summary TEXT,
    content TEXT,
    image_url TEXT,
    video_url TEXT,
    impact_type TEXT,
    location TEXT,
    beneficiaries_count INTEGER DEFAULT 0,
    is_featured BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ============================================
-- 8. LEARNING (Bee Learn)
-- ============================================

-- Learning Modules
CREATE TABLE IF NOT EXISTS learning_modules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    thumbnail_url TEXT,
    category TEXT, -- 'Basic', 'Advanced'
    difficulty_level TEXT DEFAULT 'beginner', -- 'beginner', 'intermediate', 'expert'
    duration_minutes INTEGER DEFAULT 0,
    is_free BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Learning Lessons
CREATE TABLE IF NOT EXISTS learning_lessons (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    module_id UUID REFERENCES learning_modules(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT,
    video_url TEXT,
    duration_minutes INTEGER DEFAULT 0,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ============================================
-- 9. CONTENT & COMMITMENT TABLES
-- ============================================

-- SDGs (Sustainable Development Goals)
CREATE TABLE IF NOT EXISTS sdgs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    number INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    impact TEXT,
    color TEXT,
    icon TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ESG Pillars
CREATE TABLE IF NOT EXISTS esg_pillars (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL, -- Environmental, Social, Governance
    icon TEXT,
    color_gradient TEXT,
    summary_impact TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ESG Initiatives
CREATE TABLE IF NOT EXISTS esg_initiatives (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pillar_id UUID REFERENCES esg_pillars(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Company Values
CREATE TABLE IF NOT EXISTS company_values (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ============================================
-- 10. USER PROFILES
-- ============================================

-- User Profiles (Extends Supabase Auth)
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    phone TEXT,
    avatar_url TEXT,
    role TEXT DEFAULT 'customer', -- 'customer', 'farmer', 'admin'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Function to handle new user creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user_profiles (id, first_name, last_name, avatar_url, role)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data ->> 'first_name',
    NEW.raw_user_meta_data ->> 'last_name',
    NEW.raw_user_meta_data ->> 'avatar_url',
    COALESCE(NEW.raw_user_meta_data ->> 'role', 'customer')
  );
  RETURN NEW;
END;
$$;

-- Trigger to call the function
-- Note: Trigger creation assumes auth schema access. If running in SQL editor, basic privileges may vary.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ============================================
-- 10. ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================

-- Enable RLS on all tables (Batch operation)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE farmers ENABLE ROW LEVEL SECURITY;
ALTER TABLE apiaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE hives ENABLE ROW LEVEL SECURITY;
ALTER TABLE harvests ENABLE ROW LEVEL SECURITY;
ALTER TABLE processing_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE pollination_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE newsletter_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE pollination_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE pollination_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE crops_pollinated ENABLE ROW LEVEL SECURITY;
ALTER TABLE esg_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE impact_stories ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE sdgs ENABLE ROW LEVEL SECURITY;
ALTER TABLE esg_pillars ENABLE ROW LEVEL SECURITY;
ALTER TABLE esg_initiatives ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- Public read access policies for everything (simplified for visibility)
-- In production, some of these would be restricted to authenticated users
DO $$ 
DECLARE 
    tbl_name text;
BEGIN
    FOR tbl_name IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_type = 'BASE TABLE'
        AND table_name NOT IN ('orders', 'order_items', 'contact_submissions', 'pollination_requests', 'newsletter_subscriptions', 'job_applications', 'user_profiles')
    LOOP
        EXECUTE format('CREATE POLICY "Public read for %I" ON %I FOR SELECT USING (true);', tbl_name, tbl_name);
    END LOOP;
END $$;

-- Specific policies for user-generated data
CREATE POLICY "Users can view own profile" ON user_profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON user_profiles FOR UPDATE USING (auth.uid() = id);

-- Write policies for public forms
CREATE POLICY "Public can submit contact" ON contact_submissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can submit pollination requests" ON pollination_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can subscribe to newsletter" ON newsletter_subscriptions FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can apply for jobs" ON job_applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can create orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can add items to orders" ON order_items FOR INSERT WITH CHECK (true);

-- ============================================
-- 11. INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_batches_batch_code ON batches(batch_code);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_learning_modules_slug ON learning_modules(slug);
CREATE INDEX IF NOT EXISTS idx_crops_pollinated_slug ON crops_pollinated(slug);
CREATE INDEX IF NOT EXISTS idx_impact_stories_slug ON impact_stories(slug);
CREATE INDEX IF NOT EXISTS idx_farmers_farmer_id ON farmers(farmer_id);
CREATE INDEX IF NOT EXISTS idx_apiaries_apiary_code ON apiaries(apiary_code);
CREATE INDEX IF NOT EXISTS idx_hives_hive_code ON hives(hive_code);
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders(order_number);
