/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CropsWePollinateRouteImport } from './routes/crops-we-pollinate'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PandaMitiRouteImport } from './routes/panda-miti'
import { Route as SharedRunIdRouteImport } from './routes/shared-run.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicBeegptRouteImport } from './routes/api/public/beegpt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsWePollinateRoute = CropsWePollinateRouteImport.update({
  id: '/crops-we-pollinate',
  path: '/crops-we-pollinate',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PandaMitiRoute = PandaMitiRouteImport.update({
  id: '/panda-miti',
  path: '/panda-miti',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRunIdRoute = SharedRunIdRouteImport.update({
  id: '/shared-run/$id',
  path: '/shared-run/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBeegptRoute = ApiPublicBeegptRouteImport.update({
  id: '/api/public/beegpt',
  path: '/api/public/beegpt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/crops-we-pollinate': typeof CropsWePollinateRoute
  '/our-story': typeof OurStoryRoute
  '/panda-miti': typeof PandaMitiRoute
  '/shared-run/$id': typeof SharedRunIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/beegpt': typeof ApiPublicBeegptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/crops-we-pollinate': typeof CropsWePollinateRoute
  '/our-story': typeof OurStoryRoute
  '/panda-miti': typeof PandaMitiRoute
  '/shared-run/$id': typeof SharedRunIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/beegpt': typeof ApiPublicBeegptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/crops-we-pollinate': typeof CropsWePollinateRoute
  '/our-story': typeof OurStoryRoute
  '/panda-miti': typeof PandaMitiRoute
  '/shared-run/$id': typeof SharedRunIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/beegpt': typeof ApiPublicBeegptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blogs'
    | '/careers'
    | '/crops-we-pollinate'
    | '/our-story'
    | '/panda-miti'
    | '/shared-run/$id'
    | '/.lovable/oauth/consent'
    | '/api/public/beegpt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blogs'
    | '/careers'
    | '/crops-we-pollinate'
    | '/our-story'
    | '/panda-miti'
    | '/shared-run/$id'
    | '/.lovable/oauth/consent'
    | '/api/public/beegpt'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/blogs'
    | '/careers'
    | '/crops-we-pollinate'
    | '/our-story'
    | '/panda-miti'
    | '/shared-run/$id'
    | '/.lovable/oauth/consent'
    | '/api/public/beegpt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogsRoute: typeof BlogsRoute
  CareersRoute: typeof CareersRoute
  CropsWePollinateRoute: typeof CropsWePollinateRoute
  OurStoryRoute: typeof OurStoryRoute
  PandaMitiRoute: typeof PandaMitiRoute
  SharedRunIdRoute: typeof SharedRunIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicBeegptRoute: typeof ApiPublicBeegptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops-we-pollinate': {
      id: '/crops-we-pollinate'
      path: '/crops-we-pollinate'
      fullPath: '/crops-we-pollinate'
      preLoaderRoute: typeof CropsWePollinateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panda-miti': {
      id: '/panda-miti'
      path: '/panda-miti'
      fullPath: '/panda-miti'
      preLoaderRoute: typeof PandaMitiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-run/$id': {
      id: '/shared-run/$id'
      path: '/shared-run/$id'
      fullPath: '/shared-run/$id'
      preLoaderRoute: typeof SharedRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/beegpt': {
      id: '/api/public/beegpt'
      path: '/api/public/beegpt'
      fullPath: '/api/public/beegpt'
      preLoaderRoute: typeof ApiPublicBeegptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogsRoute: BlogsRoute,
  CareersRoute: CareersRoute,
  CropsWePollinateRoute: CropsWePollinateRoute,
  OurStoryRoute: OurStoryRoute,
  PandaMitiRoute: PandaMitiRoute,
  SharedRunIdRoute: SharedRunIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicBeegptRoute: ApiPublicBeegptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
