/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BeeyieldDashboardRouteImport } from './routes/beeyield-dashboard'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CommitmentRouteImport } from './routes/commitment'
import { Route as CropsWePollinateRouteImport } from './routes/crops-we-pollinate'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PandaMitiRouteImport } from './routes/panda-miti'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShopDashboardRouteImport } from './routes/shop-dashboard'
import { Route as SharedRunIdRouteImport } from './routes/shared-run.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicBeegptRouteImport } from './routes/api/public/beegpt'
import { Route as ApiShopCardsRouteImport } from './routes/api/shop/cards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BeeyieldDashboardRoute = BeeyieldDashboardRouteImport.update({
  id: '/beeyield-dashboard',
  path: '/beeyield-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitmentRoute = CommitmentRouteImport.update({
  id: '/commitment',
  path: '/commitment',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsWePollinateRoute = CropsWePollinateRouteImport.update({
  id: '/crops-we-pollinate',
  path: '/crops-we-pollinate',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PandaMitiRoute = PandaMitiRouteImport.update({
  id: '/panda-miti',
  path: '/panda-miti',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopDashboardRoute = ShopDashboardRouteImport.update({
  id: '/shop-dashboard',
  path: '/shop-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRunIdRoute = SharedRunIdRouteImport.update({
  id: '/shared-run/$id',
  path: '/shared-run/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBeegptRoute = ApiPublicBeegptRouteImport.update({
  id: '/api/public/beegpt',
  path: '/api/public/beegpt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopCardsRoute = ApiShopCardsRouteImport.update({
  id: '/api/shop/cards',
  path: '/api/shop/cards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/beeyield-dashboard': typeof BeeyieldDashboardRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/commitment': typeof CommitmentRoute
  '/crops-we-pollinate': typeof CropsWePollinateRoute
  '/esg': typeof EsgRoute
  '/impact': typeof ImpactRoute
  '/our-story': typeof OurStoryRoute
  '/panda-miti': typeof PandaMitiRoute
  '/shop': typeof ShopRoute
  '/shop-dashboard': typeof ShopDashboardRoute
  '/shared-run/$id': typeof SharedRunIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/beegpt': typeof ApiPublicBeegptRoute
  '/api/shop/cards': typeof ApiShopCardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/beeyield-dashboard': typeof BeeyieldDashboardRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/commitment': typeof CommitmentRoute
  '/crops-we-pollinate': typeof CropsWePollinateRoute
  '/esg': typeof EsgRoute
  '/impact': typeof ImpactRoute
  '/our-story': typeof OurStoryRoute
  '/panda-miti': typeof PandaMitiRoute
  '/shop': typeof ShopRoute
  '/shop-dashboard': typeof ShopDashboardRoute
  '/shared-run/$id': typeof SharedRunIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/beegpt': typeof ApiPublicBeegptRoute
  '/api/shop/cards': typeof ApiShopCardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/beeyield-dashboard': typeof BeeyieldDashboardRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/commitment': typeof CommitmentRoute
  '/crops-we-pollinate': typeof CropsWePollinateRoute
  '/esg': typeof EsgRoute
  '/impact': typeof ImpactRoute
  '/our-story': typeof OurStoryRoute
  '/panda-miti': typeof PandaMitiRoute
  '/shop': typeof ShopRoute
  '/shop-dashboard': typeof ShopDashboardRoute
  '/shared-run/$id': typeof SharedRunIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/beegpt': typeof ApiPublicBeegptRoute
  '/api/shop/cards': typeof ApiShopCardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/beeyield-dashboard'
    | '/blogs'
    | '/careers'
    | '/commitment'
    | '/crops-we-pollinate'
    | '/esg'
    | '/impact'
    | '/our-story'
    | '/panda-miti'
    | '/shop'
    | '/shop-dashboard'
    | '/shared-run/$id'
    | '/.lovable/oauth/consent'
    | '/api/public/beegpt'
    | '/api/shop/cards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/beeyield-dashboard'
    | '/blogs'
    | '/careers'
    | '/commitment'
    | '/crops-we-pollinate'
    | '/esg'
    | '/impact'
    | '/our-story'
    | '/panda-miti'
    | '/shop'
    | '/shop-dashboard'
    | '/shared-run/$id'
    | '/.lovable/oauth/consent'
    | '/api/public/beegpt'
    | '/api/shop/cards'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/beeyield-dashboard'
    | '/blogs'
    | '/careers'
    | '/commitment'
    | '/crops-we-pollinate'
    | '/esg'
    | '/impact'
    | '/our-story'
    | '/panda-miti'
    | '/shop'
    | '/shop-dashboard'
    | '/shared-run/$id'
    | '/.lovable/oauth/consent'
    | '/api/public/beegpt'
    | '/api/shop/cards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BeeyieldDashboardRoute: typeof BeeyieldDashboardRoute
  BlogsRoute: typeof BlogsRoute
  CareersRoute: typeof CareersRoute
  CommitmentRoute: typeof CommitmentRoute
  CropsWePollinateRoute: typeof CropsWePollinateRoute
  EsgRoute: typeof EsgRoute
  ImpactRoute: typeof ImpactRoute
  OurStoryRoute: typeof OurStoryRoute
  PandaMitiRoute: typeof PandaMitiRoute
  ShopRoute: typeof ShopRoute
  ShopDashboardRoute: typeof ShopDashboardRoute
  SharedRunIdRoute: typeof SharedRunIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicBeegptRoute: typeof ApiPublicBeegptRoute
  ApiShopCardsRoute: typeof ApiShopCardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beeyield-dashboard': {
      id: '/beeyield-dashboard'
      path: '/beeyield-dashboard'
      fullPath: '/beeyield-dashboard'
      preLoaderRoute: typeof BeeyieldDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commitment': {
      id: '/commitment'
      path: '/commitment'
      fullPath: '/commitment'
      preLoaderRoute: typeof CommitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops-we-pollinate': {
      id: '/crops-we-pollinate'
      path: '/crops-we-pollinate'
      fullPath: '/crops-we-pollinate'
      preLoaderRoute: typeof CropsWePollinateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panda-miti': {
      id: '/panda-miti'
      path: '/panda-miti'
      fullPath: '/panda-miti'
      preLoaderRoute: typeof PandaMitiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-dashboard': {
      id: '/shop-dashboard'
      path: '/shop-dashboard'
      fullPath: '/shop-dashboard'
      preLoaderRoute: typeof ShopDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-run/$id': {
      id: '/shared-run/$id'
      path: '/shared-run/$id'
      fullPath: '/shared-run/$id'
      preLoaderRoute: typeof SharedRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/beegpt': {
      id: '/api/public/beegpt'
      path: '/api/public/beegpt'
      fullPath: '/api/public/beegpt'
      preLoaderRoute: typeof ApiPublicBeegptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/cards': {
      id: '/api/shop/cards'
      path: '/api/shop/cards'
      fullPath: '/api/shop/cards'
      preLoaderRoute: typeof ApiShopCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BeeyieldDashboardRoute: BeeyieldDashboardRoute,
  BlogsRoute: BlogsRoute,
  CareersRoute: CareersRoute,
  CommitmentRoute: CommitmentRoute,
  CropsWePollinateRoute: CropsWePollinateRoute,
  EsgRoute: EsgRoute,
  ImpactRoute: ImpactRoute,
  OurStoryRoute: OurStoryRoute,
  PandaMitiRoute: PandaMitiRoute,
  ShopRoute: ShopRoute,
  ShopDashboardRoute: ShopDashboardRoute,
  SharedRunIdRoute: SharedRunIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicBeegptRoute: ApiPublicBeegptRoute,
  ApiShopCardsRoute: ApiShopCardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
