
-- Create Tables
CREATE TABLE IF NOT EXISTS public.case_study_categories (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.case_study_stories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id TEXT REFERENCES public.case_study_categories(id) ON DELETE CASCADE,
    farmer TEXT NOT NULL,
    location TEXT NOT NULL,
    role TEXT NOT NULL,
    acres INTEGER NOT NULL,
    description TEXT NOT NULL,
    quote TEXT,
    image_url TEXT,
    stats_json JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.case_study_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.case_study_stories ENABLE ROW LEVEL SECURITY;

-- Allow public read access
DROP POLICY IF EXISTS "Public can view case study categories" ON public.case_study_categories;
CREATE POLICY "Public can view case study categories" ON public.case_study_categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view case study stories" ON public.case_study_stories;
CREATE POLICY "Public can view case study stories" ON public.case_study_stories FOR SELECT USING (true);

-- Insert Data
INSERT INTO public.case_study_categories (id, title, category_name) VALUES ('maize', 'Maize Pollination', 'Cereal Crop') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('maize', 'James Mwangi', 'Kibwezi, Makueni', 'Commercial Maize Farmer', 40, 'My 40-acre maize farm in Kibwezi has always been decent, but plateaued. I was skeptical about bees for wind-pollinated maize, but BeeYield proved me wrong. The cobs are filled to the tip, pushing my yield per acre up by 18%.', 'I was skeptical at first because maize is wind-pollinated, but the difference in cob fullness was undeniable.', '/images/maize_case.png', '[{"label":"Yield Increase","value":"+18%"},{"label":"Acres Pollinated","value":"40"},{"label":"Cob Fill","value":"100%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('maize', 'Peter Korir', 'Mbuinzau, Makueni', 'Seed Maize Producer', 100, 'Seed production is a numbers game. We need every silk pollinated. BeeYield brought in high-density hives during tasseling. The resulting seed set was the highest we''ve seen in five years.', 'For seed maize, you can''t leave it to chance. The bees ensured every silk was hit.', 'https://images.unsplash.com/photo-1634467524884-897d0af5e104?auto=format&fit=crop&q=80&w=1200', '[{"label":"Seed Set","value":"99%"},{"label":"Acres Pollinated","value":"100"},{"label":"Grade","value":"Premium"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('maize', 'Alice Wanjiku', 'Makindu, Makueni', 'Mixed Crop Farmer', 15, 'I intercrop maize with beans. The bees helped both. My maize cobs are heavier this season, and the kernels are deep and well-formed.', 'It''s not just the quantity, it''s the weight of the harvest that surprised me.', 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&q=80&w=1200', '[{"label":"Harvest Weight","value":"+15%"},{"label":"Acres Pollinated","value":"15"},{"label":"Grain fill","value":"High"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('maize', 'Robert Kemboi', 'Kibwezi, Makueni', 'Maize Farmer', 25, 'Using BeeYield''s services was a game changer for my medium-scale farm. The uniformity of the crop was excellent, making harvesting much easier.', 'Uniform growth and better filling. I''m definitely using them again next season.', 'https://images.unsplash.com/photo-1629007687834-0466be24751f?auto=format&fit=crop&q=80&w=1200', '[{"label":"Uniformity","value":"Excellent"},{"label":"Acres Pollinated","value":"25"},{"label":"Yield","value":"+12%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('maize', 'Sarah Chepkoech', 'Mbuinzau, Makueni', 'Commercial Farmer', 60, 'We farm on a large scale. BeeYield''s professionalism and the impact of their bees on our maize crop were impressive. We saw a tangible return on investment.', 'Professional service and visible results. The bees paid for themselves.', 'https://images.unsplash.com/photo-1595126868697-7c7038e827e8?auto=format&fit=crop&q=80&w=1200', '[{"label":"ROI","value":"Positive"},{"label":"Acres Pollinated","value":"60"},{"label":"Quality","value":"High"}]'::jsonb);
INSERT INTO public.case_study_categories (id, title, category_name) VALUES ('sunflower', 'Sunflower Production', 'Oilseed Crop') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('sunflower', 'Sarah Kimathi', 'Makindu, Makueni', 'Sunflower Producer', 30, 'Sunflowers and bees are a perfect match. On my 30 acres in Makindu, the difference between the starting rows near the wild bees and the center was huge. BeeYield''s hives evened that out. Full heads everywhere.', 'The bees were incredibly active. We saw full heads of seeds and higher oil extraction rates.', '/images/sunflower_case.png', '[{"label":"Oil Content","value":"+25%"},{"label":"Acres Pollinated","value":"30"},{"label":"Seed Set","value":"95%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('sunflower', 'John Omondi', 'Kibwezi, Makueni', 'Smallholder Group Lead', 50, 'Our cooperative consolidated 50 acres for sunflower oil. We needed consistent pollination across fragmented plots. The mobile hives did the trick, boosting our collective output.', 'Bringing bees to our scattered plots unified our harvest quality.', 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&q=80&w=1200', '[{"label":"Group Yield","value":"+30%"},{"label":"Acres Pollinated","value":"50"},{"label":"Uniformity","value":"High"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('sunflower', 'Lucas Maara', 'Mbuinzau, Makueni', 'Dryland Farmer', 12, 'Farming in semi-arid areas is tough. You need to maximize every flower. The bees ensured that the short bloom window resulted in a harvestable crop despite the heat.', 'The bees made sure the short rainy season bloom counted.', 'https://images.unsplash.com/photo-1470509037663-253afd7f0f6e?auto=format&fit=crop&q=80&w=1200', '[{"label":"Drought Resilience","value":"Improved"},{"label":"Acres Pollinated","value":"12"},{"label":"Seed Count","value":"High"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('sunflower', 'Beatrice Wanjiku', 'Makindu, Makueni', 'Sunflower Farmer', 8, 'I started small with sunflowers. BeeYield helped me understand the importance of pollination. The seeds were plump and full of oil.', 'I never knew bees could make such a difference in seed quality.', 'https://images.unsplash.com/photo-1528691503-4905106881c6?auto=format&fit=crop&q=80&w=1200', '[{"label":"Seed Quality","value":"Excellent"},{"label":"Acres Pollinated","value":"8"},{"label":"Oil %","value":"+20%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('sunflower', 'David Kiplagat', 'Kibwezi, Makueni', 'Commercial Grower', 45, 'Reliability is key for my contract farming. BeeYield delivered hives on time and the bees were strong. My harvest met all the buyer''s specifications.', 'Reliable service and strong colonies. Exactly what a commercial grower needs.', 'https://images.unsplash.com/photo-1459156212016-c812468e2115?auto=format&fit=crop&q=80&w=1200', '[{"label":"Contract Met","value":"100%"},{"label":"Acres Pollinated","value":"45"},{"label":"Yield","value":"+15%"}]'::jsonb);
INSERT INTO public.case_study_categories (id, title, category_name) VALUES ('mangoes', 'Mango Exports', 'Fruit Orchard') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('mangoes', 'David Mutua', 'Mbuinzau, Makueni', 'Orchard Manager', 25, 'Export markets demand perfection. Reduced early fruit drop was my main goal. BeeYield''s pollinators kept the fruit on the tree and improved the shape.', 'Our export rejection rate dropped significantly. The fruit uniformity was the best in a decade.', '/images/mango_case.png', '[{"label":"Retention","value":"+30%"},{"label":"Acres Pollinated","value":"25"},{"label":"Export Grade","value":"Premium"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('mangoes', 'Esther Muli', 'Kibwezi, Makueni', 'Organic Mango Farmer', 10, 'As an organic farmer, I rely on nature. Adding managed hives boosted my bio-intensive approach. The bees were aggressive workers, hitting every flower spike.', 'Simple, natural, and effective. The bees did more for my crop than any fertilizer.', 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=1200', '[{"label":"Fruit Set","value":"+25%"},{"label":"Acres Pollinated","value":"10"},{"label":"Size","value":"Large"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('mangoes', 'Rashid Ali', 'Makindu, Makueni', 'Coastal Grower', 40, 'Our coastal mango varieties flower profusely. We needed a workforce to match. BeeYield deployed 20 hives for my 40 acres, ensuring coverage spread to the canopy top.', 'We saw bees working even the top branches where we usually lose fruit.', 'https://images.unsplash.com/photo-1519999482648-25049ddd37b1?auto=format&fit=crop&q=80&w=1200', '[{"label":"Canopy Reach","value":"100%"},{"label":"Acres Pollinated","value":"40"},{"label":"Volume","value":"+40 Tons"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('mangoes', 'Joseph Kyalo', 'Kibwezi, Makueni', 'Mango Farmer', 18, 'Drought conditions usually hit my yield hard. However, with the bees maximizing pollination during the short flowering burst, I still managed a respectable harvest.', 'The bees saved my season during a tough dry spell.', 'https://images.unsplash.com/photo-1596484393963-47a32c256247?auto=format&fit=crop&q=80&w=1200', '[{"label":"Resilience","value":"High"},{"label":"Acres Pollinated","value":"18"},{"label":"Fruit Count","value":"Good"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('mangoes', 'Mary Nduku', 'Mbuinzau, Makueni', 'Small Scale Exporter', 5, 'Quality over quantity is my motto. Bee pollination gave my mangoes the size and blush needed for the premium export crates.', 'Perfectly shaped fruit that gets the best price.', 'https://images.unsplash.com/photo-1536511132770-4daf7575620d?auto=format&fit=crop&q=80&w=1200', '[{"label":"Price Premium","value":"+20%"},{"label":"Acres Pollinated","value":"5"},{"label":"Quality","value":"Top"}]'::jsonb);
INSERT INTO public.case_study_categories (id, title, category_name) VALUES ('beans', 'Bean Yields', 'Legumes') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('beans', 'Alice Chebet', 'Makindu, Makueni', 'Mixed Crop Farmer', 18, 'Beans usually take care of themselves, but I wanted more. The ''tripping'' effect of the bees was real. My pods filled out completely, no air pockets inside.', 'BeeYield''s service helped us achieve a bumper harvest. The pods were consistently full.', '/images/beans_case.png', '[{"label":"Pod Fill","value":"98%"},{"label":"Acres Pollinated","value":"18"},{"label":"Harvest Time","value":"Uniform"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('beans', 'Geoffrey Otieno', 'Kibwezi, Makueni', 'Soya & Bean Farmer', 22, 'I grew soya and climbing beans. The bees worked both. The synchronized flowering and pod set made mechanical harvesting totally viable this year.', 'Uniform maturity saved me days of labor during harvest.', 'https://images.unsplash.com/photo-1515543904379-3d757afe72e3?auto=format&fit=crop&q=80&w=600', '[{"label":"Labor Saving","value":"2 Days"},{"label":"Acres Pollinated","value":"22"},{"label":"Yield","value":"+22%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('beans', 'Rose Auma', 'Mbuinzau, Makueni', 'Bean Farmer', 10, 'My bean crop has never looked this green and productive. The bees were constantly buzzing around. I harvested more bags per acre than ever before.', 'Record-breaking harvest for my farm.', 'https://images.unsplash.com/photo-1567306301408-9b74779a11af?auto=format&fit=crop&q=80&w=1200', '[{"label":"Yield/Acre","value":"+20%"},{"label":"Acres Pollinated","value":"10"},{"label":"Pod Count","value":"High"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('beans', 'Paul Wafula', 'Makindu, Makueni', 'Commercial Farmer', 35, 'Rolling out BeeYield''s hives across my 35 acres ensured consistent pod setting. The resulting uniformity in the bean size was perfect for processing.', 'Consistency is key for canning beans, and the bees delivered.', 'https://images.unsplash.com/photo-1594247065091-62d3851b9e07?auto=format&fit=crop&q=80&w=1200', '[{"label":"Consistency","value":"High"},{"label":"Acres Pollinated","value":"35"},{"label":"Rejection","value":"Low"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('beans', 'Janet Kemunto', 'Kibwezi, Makueni', 'Mixed Farmer', 7, 'With limited land, I have to maximize efficiency. The bees helped my climbing beans produce pods right to the top of the poles.', 'Maximum production from every square foot of land.', 'https://images.unsplash.com/photo-1615485500704-8e99099d9d0f?auto=format&fit=crop&q=80&w=1200', '[{"label":"Efficiency","value":"Maximized"},{"label":"Acres Pollinated","value":"7"},{"label":"Vertical Yield","value":"High"}]'::jsonb);
INSERT INTO public.case_study_categories (id, title, category_name) VALUES ('sisal', 'Sisal Agave', 'Fiber Crop') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('sisal', 'Estate Manager', 'Mbuinzau, Makueni', 'Sisal Plantation', 500, 'On 500 acres, biodiversity is a concern. The bees turned our flowering poles into a honey factory without disturbing seed production. A win-win for ecology and revenue.', 'Integrating bees created a new revenue stream from honey and improved local ecology.', '/images/sisal_case.png', '[{"label":"Honey","value":"500kg"},{"label":"Acres Managed","value":"500"},{"label":"Sustainability","value":"High"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('sisal', 'Conservation Trust', 'Makindu, Makueni', 'Land Management', 200, 'We manage sisal barriers. The bees helped naturalize the fence lines and supported the surrounding wildflowers, boosting the overall insect population.', 'A perfect example of productive conservation.', 'https://images.unsplash.com/photo-1509587584298-0f3b3a3a1797?auto=format&fit=crop&q=80&w=1200', '[{"label":"Eco-Health","value":"Restored"},{"label":"Acres Managed","value":"200"},{"label":"Wildflowers","value":"Thriving"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('sisal', 'Community Coop', 'Kibwezi, Makueni', 'Communal Land', 100, 'Our community uses sisal for crafts. The honey produced by the bees from the sisal flowers gave us an additional income source during the dry season.', 'Honey from sisal? A sweet surprise for our community.', 'https://images.unsplash.com/photo-1590486803833-1c5dc8ce2ac3?auto=format&fit=crop&q=80&w=1200', '[{"label":"Income","value":"Diversified"},{"label":"Acres Managed","value":"100"},{"label":"Honey Quality","value":"Unique"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('sisal', 'Private Rancher', 'Mbuinzau, Makueni', 'Ranching', 1000, 'Using bees on our sisal boundaries helps deter elephants while fixing carbon through better plant growth. It''s a natural barrier system.', 'Bees, sisal, and elephants - a delicate but effective balance.', 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=1200', '[{"label":"Conflict","value":"Reduced"},{"label":"Acres Managed","value":"1000"},{"label":"Eco-Balance","value":"Good"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('sisal', 'Coastal Plantations', 'Makindu, Makueni', 'Commercial Agave', 300, 'We are experimenting with massive scale pollination. Initial results show healthier parent plants and more viable bulbils for replanting.', 'Investing in the future of our plantation stock.', 'https://images.unsplash.com/photo-1599598425947-658b44670c5e?auto=format&fit=crop&q=80&w=1200', '[{"label":"Stock Health","value":"+10%"},{"label":"Acres Managed","value":"300"},{"label":"Propagation","value":"Easy"}]'::jsonb);
INSERT INTO public.case_study_categories (id, title, category_name) VALUES ('oranges', 'Citrus Quality', 'Fruit Orchard') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('oranges', 'Hassan Juma', 'Kibwezi, Makueni', 'Citrus Farmer', 15, 'My 15-acre orange grove had issues with fruit size. BeeYield ensured that every blossom got visited multiple times. The result? Big, heavy, juicy oranges.', 'The quality improved drastically. They are larger, sweeter, and fetch a better price.', 'https://images.unsplash.com/photo-1547514701-42782101795e?auto=format&fit=crop&q=80&w=1200', '[{"label":"Juice Content","value":"High"},{"label":"Acres Pollinated","value":"15"},{"label":"Fruit Size","value":"Large"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('oranges', 'Mariam Abdi', 'Mbuinzau, Makueni', 'Orchard Owner', 20, 'We target the premium juice market. Brix levels are king. The stress-free pollination provided by the bees seemed to concentrate sugars better.', 'Our sweetness levels hit a record high this season.', 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&q=80&w=1200', '[{"label":"Brix Level","value":"Top Tier"},{"label":"Acres Pollinated","value":"20"},{"label":"Bloom Coverage","value":"100%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('oranges', 'Ali Swaleh', 'Makindu, Makueni', 'Citrus Grower', 10, 'Salt air and heat can be tough on blossoms. The bees worked fast in the cool mornings. My lime trees are loaded with fruit this year.', 'Excellent set even with our rough coastal climate.', 'https://images.unsplash.com/photo-1559181567-c3190ca9959b?auto=format&fit=crop&q=80&w=1200', '[{"label":"Climate Adaptation","value":"High"},{"label":"Acres Pollinated","value":"10"},{"label":"Yield","value":"+25%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('oranges', 'Farm Manager', 'Kibwezi, Makueni', 'Pixie Oranges', 50, 'Pixie oranges need to be seedless and sweet. Controlled pollination helps maintain quality. The bees did a great job navigating our dense orchard.', 'Dense canopy? No problem for BeeYield''s hives.', 'https://images.unsplash.com/photo-1621696417779-795244793444?auto=format&fit=crop&q=80&w=1200', '[{"label":"Coverage","value":"100%"},{"label":"Acres Pollinated","value":"50"},{"label":"Fruit Quality","value":"Premium"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('oranges', 'Grace Mwende', 'Mbuinzau, Makueni', 'Lemon Farmer', 5, 'I wanted to extend my harvest season. The bees helped synchronize the bloom, so I had a massive, manageable harvest instead of sporadic picking.', 'Synchronized harvest simplified my labor planning.', 'https://images.unsplash.com/photo-1595123049102-140a6e54145b?auto=format&fit=crop&q=80&w=1200', '[{"label":"Sync","value":"Perfect"},{"label":"Acres Pollinated","value":"5"},{"label":"Yield","value":"+18%"}]'::jsonb);
INSERT INTO public.case_study_categories (id, title, category_name) VALUES ('vegetables', 'Mixed Vegetables', 'Horticulture') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('vegetables', 'Grace Wanjiku', 'Makindu, Makueni', 'Horticulturist', 8, 'I grow 12 types of vegetables on 8 intensive acres. The bees are generalists—they hit the peppers, the courgettes, everything. My rejection rate dropped by 15%.', 'We grow a bit of everything, and the bees have helped boost production across the board.', 'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?auto=format&fit=crop&q=80&w=1200', '[{"label":"Crop Diversity","value":"12 Types"},{"label":"Acres Pollinated","value":"8"},{"label":"Defects","value":"-15%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('vegetables', 'Njoroge K.', 'Kibwezi, Makueni', 'Market Gardener', 5, 'For the city market, looks matter. Misshapen courgettes don''t sell. My bee-pollinated crop was straight and glossy.', 'The visual appeal of the produce is just different now.', 'https://images.unsplash.com/photo-1595855709915-f5b2b295ba5d?auto=format&fit=crop&q=80&w=1200', '[{"label":"Marketability","value":"+20%"},{"label":"Acres Pollinated","value":"5"},{"label":"Shape","value":"Perfect"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('vegetables', 'Horti-Coop', 'Mbuinzau, Makueni', 'Export Veg', 20, 'French beans for export require delicate handling. The bees pollinated the flowers without damaging the delicate plants. Yields are up across the cooperative.', 'Gentle, effective pollination for high-value crops.', 'https://images.unsplash.com/photo-1557844352-761f2565b576?auto=format&fit=crop&q=80&w=1200', '[{"label":"Export Quality","value":"Verified"},{"label":"Acres Pollinated","value":"20"},{"label":"Yield","value":"+12%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('vegetables', 'Local school farm', 'Makindu, Makueni', 'Educational Farm', 2, 'We use the hives for education and pollination. The pumpkins and squashes grown by the students are record-breaking size this year thanks to the bees.', 'Education and production going hand in hand.', 'https://images.unsplash.com/photo-1621459586195-2cc677054f0c?auto=format&fit=crop&q=80&w=1200', '[{"label":"Size","value":"Record"},{"label":"Acres Pollinated","value":"2"},{"label":"Learning","value":"High"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('vegetables', 'Urban Grower', 'Kibwezi, Makueni', 'Intensive Farming', 1, 'Even on 1 acre, density matters. The bees ensured that my vertical garden towers of capsicum set fruit at every level.', 'Maximizing yield in minimum space.', 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&q=80&w=1200', '[{"label":"Vertical Set","value":"100%"},{"label":"Acres Pollinated","value":"1"},{"label":"Density","value":"High"}]'::jsonb);
INSERT INTO public.case_study_categories (id, title, category_name) VALUES ('tomatoes', 'Tomato Greenhouses', 'Greenhouse') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('tomatoes', 'Peter Njoroge', 'Mbuinzau, Makueni', 'Greenhouse Manager', 3, '3 acres under plastic. We used to vibrate flowers by hand. The bees do it 40 hours a week for us. The savings on labor alone paid for the service.', 'Before bees, we had to mechanically vibrate flowers. The bees do it better and faster.', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=1200', '[{"label":"Labor Saved","value":"40 Hrs/Wk"},{"label":"Acres Pollinated","value":"3"},{"label":"Fruit Set","value":"99%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('tomatoes', 'Sarah Jenkins', 'Makindu, Makueni', 'Export Greenhouse', 10, 'Export tomatoes need to be uniform size. The bumblebee-like buzzing of BeeYield''s hives ensured every flower released pollen completely.', 'Uniformity is our currency. The bees printed money for us this year.', 'https://images.unsplash.com/photo-1561136120-f19b16ea9399?auto=format&fit=crop&q=80&w=1200', '[{"label":"Grade 1","value":"95%"},{"label":"Acres Pollinated","value":"10"},{"label":"Speed","value":"Fast"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('tomatoes', 'James Kinyanjui', 'Kibwezi, Makueni', 'Metro Greenhouse', 5, 'Supplying Nairobi hotels requires consistency. With bees, I don''t miss a beat. Every cluster of flowers turns into a cluster of tomatoes.', 'Reliable production week after week.', 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?auto=format&fit=crop&q=80&w=1200', '[{"label":"Consistency","value":"High"},{"label":"Acres Pollinated","value":"5"},{"label":"Fruit Drop","value":"Zero"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('tomatoes', 'Bio-Farm Ltd', 'Mbuinzau, Makueni', 'Organic Greenhouse', 8, 'We can''t use hormones for fruit set. Bees are the only natural solution. They fit perfectly into our certified organic workflow.', 'The natural choice for organic certification.', 'https://images.unsplash.com/photo-1558818498-28c1e002b655?auto=format&fit=crop&q=80&w=1200', '[{"label":"Organic","value":"Certified"},{"label":"Acres Pollinated","value":"8"},{"label":"Set Rate","value":"98%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('tomatoes', 'Research Group', 'Makindu, Makueni', 'Research Greenhouse', 1, 'Monitoring the efficiency of bee pollination vs manual. The evidence is clear: bees are efficient and produce heavier fruit.', 'Nature does it best.', 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&q=80&w=1200', '[{"label":"Efficiency","value":"3x"},{"label":"Acres Pollinated","value":"1"},{"label":"Weight","value":"+15%"}]'::jsonb);
INSERT INTO public.case_study_categories (id, title, category_name) VALUES ('onions', 'Onion Seed', 'Seed Production') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('onions', 'Seed Co. Rep', 'Kibwezi, Makueni', 'Production Lead', 50, 'On 50 acres of hybrid onion, you can''t fake it. We placed 4 hives per acre. The activity was frantic. We broke our site record for seed yield per acre.', 'We are in the business of seeds, and bees are our most valuable employees.', '/images/onion-plantation.png', '[{"label":"Seed Yield","value":"+35%"},{"label":"Acres Pollinated","value":"50"},{"label":"Hive Density","value":"4/Acre"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('onions', 'Contract Farmer', 'Mbuinzau, Makueni', 'Irrigation Scheme', 15, 'Pollination is usually our bottleneck. Not this time. The coverage was so good we had to prop up the seed heads due to weight.', 'Heaviest heads I''ve ever seen.', 'https://images.unsplash.com/photo-1620574387735-3624d75b2dbc?auto=format&fit=crop&q=80&w=1200', '[{"label":"Germination","value":"92%"},{"label":"Acres Pollinated","value":"15"},{"label":"Weight","value":"High"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('onions', 'Daniel Moi', 'Makindu, Makueni', 'Seed Grower', 10, 'High altitude onion seed is valuable. The bees adapted well to the cooler mornings and ensured a profitable harvest.', 'Adaptable bees for our unique climate.', 'https://images.unsplash.com/photo-1623226996614-727581559869?auto=format&fit=crop&q=80&w=1200', '[{"label":"Adaptability","value":"Good"},{"label":"Acres Pollinated","value":"10"},{"label":"Profit","value":"+20%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('onions', 'Rift Valley Seeds', 'Kibwezi, Makueni', 'Commercial Seed', 60, 'We need purity. BeeYield managed the isolation distances and hive placement perfectly. Pure, high-quality hybrid seed was the result.', 'Purity and yield - the holy grail of seed production.', 'https://images.unsplash.com/photo-1621459586326-c23f798889c3?auto=format&fit=crop&q=80&w=1200', '[{"label":"Genetic Purity","value":"100%"},{"label":"Acres Pollinated","value":"60"},{"label":"Yield","value":"+30%"}]'::jsonb);
INSERT INTO public.case_study_stories (category_id, farmer, location, role, acres, description, quote, image_url, stats_json) VALUES ('onions', 'Smallholder Group', 'Mbuinzau, Makueni', 'Community Scheme', 25, 'Pooling our land for seed production was risky. The bees de-risked it by ensuring a bumper crop for everyone involved.', 'A collective success story.', 'https://images.unsplash.com/photo-1618382025171-47752e5a2db3?auto=format&fit=crop&q=80&w=1200', '[{"label":"Success","value":"Shared"},{"label":"Acres Pollinated","value":"25"},{"label":"Risk","value":"Lowered"}]'::jsonb);
