-- 0. Clean up existing (potentially broken) tables
DROP TABLE IF EXISTS public.disease_detections CASCADE;
DROP TABLE IF EXISTS public.land_readings CASCADE;
DROP TABLE IF EXISTS public.sensor_readings CASCADE;

-- 1. Create In-Hive Readings Table
CREATE TABLE public.sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hive_id UUID REFERENCES public.hives(id) NOT NULL,
    user_id UUID REFERENCES auth.users(id),
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    weight_kg DECIMAL(5,2),
    temp_internal DECIMAL(4,1),
    humidity_internal DECIMAL(4,1),
    acoustic_freq INTEGER
);

-- 2. Create Land/Environmental Readings Table
CREATE TABLE IF NOT EXISTS public.land_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apiary_id UUID REFERENCES public.apiaries(id) NOT NULL,
    user_id UUID REFERENCES auth.users(id),
    device_sn TEXT, -- e.g., 'WEATHER-STATION-01'
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    soil_moisture DECIMAL(4,1), -- Percentage
    rainfall_mm DECIMAL(6,2),
    ambient_temp DECIMAL(4,1),
    wind_speed_kmh DECIMAL(5,1)
);

-- 3. Create Disease Detection Events
CREATE TABLE IF NOT EXISTS public.disease_detections (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    hive_id UUID REFERENCES public.hives(id) NOT NULL,
    user_id UUID REFERENCES auth.users(id),
    detected_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    threat_type TEXT NOT NULL, -- 'varroa', 'afb', 'beetle'
    confidence DECIMAL(3,2), -- 0.00 to 1.00
    severity TEXT DEFAULT 'low', -- low, medium, critical
    image_evidence_url TEXT,
    status TEXT DEFAULT 'unresolved' -- unresolved, treated, false_positive
);

-- 4. Performance Indexes (Crucial for Graphing Speed)
CREATE INDEX IF NOT EXISTS idx_sensor_hive_time ON sensor_readings (hive_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_land_apiary_time ON land_readings (apiary_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_disease_hive ON disease_detections (hive_id);

-- 5. Enable Security (RLS)
ALTER TABLE sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE land_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE disease_detections ENABLE ROW LEVEL SECURITY;

-- 6. Policies (User can only see data for Hives/Apiaries they own)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Read own sensor data') THEN
        CREATE POLICY "Read own sensor data" ON sensor_readings FOR SELECT USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Read own land data') THEN
        CREATE POLICY "Read own land data" ON land_readings FOR SELECT USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Read own disease data') THEN
        CREATE POLICY "Read own disease data" ON disease_detections FOR SELECT USING (auth.uid() = user_id);
    END IF;
END
$$;
