-- Add idempotency support and payment status to billing_ledger
-- Refined for the Oxidized Shop Engine

ALTER TABLE public.billing_ledger 
ADD COLUMN IF NOT EXISTS idempotency_key TEXT UNIQUE,
ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending' 
CHECK (payment_status IN ('pending', 'processing', 'completed', 'failed', 'refunded'));

-- Create an index on idempotency_key for fast lookups
CREATE INDEX IF NOT EXISTS idx_billing_ledger_idempotency ON public.billing_ledger(idempotency_key);

-- Add a comment to the table for clarity
COMMENT ON COLUMN public.billing_ledger.idempotency_key IS 'Unique key generated by frontend to prevent double-charging.';
COMMENT ON COLUMN public.billing_ledger.payment_status IS 'State of the financial transaction (separate from eTIMS status).';
